# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload_Cloud_Function

on:
  push:
    branches: 
    - master



jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: windows-2016
    env:
      PROJECT: ${{ SECRETS.RUN_PROJECT}}
      #SENDGRID_API_KEY: ${{ SECRETS.SENDGRID_API_KEY }}
      RUN_REGION: us-central1
      SERVICE_NAME: send_mail
    defaults:
      run:
        working-directory: emails
    steps:
    - uses: actions/checkout@v2
    - name: Set_up_Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
#     - name: Build package
#       run: |
#           pip install pytest
          #pytest main.py
    - name: Publish package
      #uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        ref: ${{ github.headref }}
        token: ${{ secrets.PYPI_API_TOKEN }}
